.TH encyfuncs 1 "2nd Jan 99" ? "encyfuncs manual"
.SH NAME
encyfuncs \- Star Trek encyclopedia interface
.SH SYNOPSIS
.B [none]
.SH DESCRIPTION
encyfuncs is an interface to the Star Trek Encyclopedia, with functions avaliable to other programs, so it is easy to write programs to use the encyclopedia.

See
.B ency.h
for exported stuff.
.B findenc
is my example program. For more information, read the source code. I will try to document it as soon as possible
.SH "SEE ALSO"
.BR findenc (1)
.SH BUGS
See 
.B BUGS
in the source directory
.SH AUTHOR
.nf
"Robert Mibus"
beemer@picknowl.com.au
mibus@hallett-cove.schools.sa.edu.au
http://www.picknowl.com.au/homepages/beemer/robonly.html
