.TH findenc 1 "2nd Jan 99" ? "findenc manual"
.SH NAME
findenc \- Star Trek encyclopedia search engine
.SH SYNOPSIS
.B findenc
.SH DESCRIPTION
Findenc is an interface to my 
.B ency
routines. It searches through Data.cxt of the Star Trek Encyclopedia and matches with an inputted string, displaying all results at the end.
.SH "SEE ALSO"
.BR encyfuncs (1)
.SH BUGS
See 
.B BUGS
in the source directory
.SH AUTHOR
.nf
"Robert Mibus"
beemer@picknowl.com.au
mibus@hallett-cove.schools.sa.edu.au
http://www.picknowl.com.au/homepages/beemer/robonly.html
