.TH FINDENC "1" "September 2000" "findenc" FSF
.SH NAME
findenc \- manual page for findenc - Searches the Star Trek encyclopedias
.SH SYNOPSIS
.B findenc
[\fIOPTION\fR...] [\fIsearch string\fR]
.SH DESCRIPTION
findenc - Searches the Star Trek encyclopedias
.TP
\fB\-\-chronology\fR
(-c)    Searches the chronology section
.TP
\fB\-\-episode\fR
(-e)    Searches the episode guide section
.IP
(Default: Search the encyclopedia section)
.TP
\fB\-\-media\fR
(-m)    Displays associated media
.TP
findenc will look in the current directory for a data file unless the environment variable ENCY_FILENAME is set to one.

