.TH HTMLENC "1" "September 2000" "htmlenc" FSF
.SH NAME
htmlenc
.SH SYNOPSIS
.B htmlenc
[\fIOPTION\fR...] [\fIsearch string\fR]
.SH DESCRIPTION
.IP
Searches the Star Trek encyclopedias
.TP
\fB\-\-chronology\fR
(-c)    Searches the chronology section
.TP
\fB\-\-episode\fR
(-e)    Searches the episode guide section
.IP
(Default: Search the encyclopedia section)
.TP
\fB\-\-media\fR
(-m)    Displays associated media
.TP
htmlenc will look in the current directory for a data file unless the environment variable ENCY_FILENAME is set to one.
