.TH scanenc "1" "September 2000" "scanenc" FSF
.SH NAME
scanenc
Scans Star Trek Encyclopedia data files
.SH SYNOPSIS
.B scanenc
[\fIdata file\fR]
.SH DESCRIPTION
.B scanenc
processes the data file from a Star Trek Encyclopedia (if possible) and reports loads of information about it and it's contents.
Look for names like *.cxt and *.dxr, they will usually be very large (well, 5-20MB).
